### ISSUE TITLE
"Laravel Kit.app" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by zakini** [tmdh/laravel-kit#40]
I'm getting this error when trying to open Laravel Kit. I've tried installing via brew and by downloading the .dmg directly from [the releases](https://github.com/tmdh/laravel-kit/releases/tag/v2.0.6).

<img width="250" alt="Screenshot 2022-03-22 at 12 38 34" src="https://user-images.githubusercontent.com/11508697/159483898-c4df933b-1c25-4b7d-8400-89840f153f0a.png">

**Comment by arafatkn** [comment]
@Zakini 
Please follow the below steps for the first time. From next time, you will be opened normally.

Open **Finder** and Go to **Applications** and Then right-click on it so that the context menu should be opened.
Then click on "Open" and it will show you a warning but you will find the "open" button inside the warning there. 
Now open the app.

https://prnt.sc/95wDH3l90TgN

**Comment by zakini** [comment]
That works, but could you sign the app so that this step isn't necessary?

**Comment by tmdh** [comment]
Code signing for macOS costs $99/yr. I can't spend that much money for a side project.

**Comment by zakini** [comment]
Ah that's totally fair. Maybe worth adding to the readme then?

**Comment by tmdh** [comment]
Added info to README.
